config/routes.rb
Rails.application.routes.draw do

  root to: 'app#top'
  
  resources :app do
    collection do
      get 'top'
    end
  end

  resources :managements do
    collection do
      get 'top'
      get 'items'
      get 'orders'
      get 'roomindex'
      get 'messageindex'
      post 'messagecreate'
      post 'roomcreate'
    end
  end

  resources :items do
    resources :stocks, only: [:edit, :update]
    collection do
      get 'search'
    end
  end

  get 'item/:id', to: 'items#checked'
  get 'seller/:id', to: 'sellers#checked'

  resources :orders, only: [:new, :create, :index] do
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :rooms, only:[:create, :index] do
    resources :messages, only: [:create, :index]
  end

  resources :favoriteitems, only: :index
  resources :favoritesellers, only: :index

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  devise_for :sellers, controllers: {
    sessions:      'sellers/sessions',
    passwords:     'sellers/passwords',
    registrations: 'sellers/registrations'
  }


  resources :sellers, only: :show

  resources :users do
    resources :charges, only: [:new, :create, :edit, :update]
  end

end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer1.html.erb
<footer class='footer'>
  <div class='footer-contents'>
    <div class='ecshop-details'>
      <h2 class='footer-content-head'>FOOD MALLについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'FOOD MALL利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='ecshop-details'>
      <h2 class='footer-content-head'>FOOD MALLを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
        <li><%= link_to 'ブランド一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='ecshop-details'>
      <h2 class='footer-content-head'>FOOD MALLについて</h2>
      <ul>
        <li><%= link_to 'FOOD MALLガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'FOOD MALLロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("logo2.PNG", class:"footer-icon2"), "#" %>
  <p>© FOOD MALL</p>
</footer>

app/views/shared/_footer2.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>FOOD MALL利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <%= image_tag "logo2.PNG", class:"second-fotter-logo"%>
</footer>

app/views/shared/_header1.html.erb
<header class="header1">
  <div class="logo1">
    <%= link_to image_tag("logo1.PNG", class:"ecshop-icon1"), items_path %>
  </div>
  <div class="nav1">
    <ul class="buttons">
      <% unless user_signed_in? %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "user-button" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "user-button" %></li>
      <% else %>
      <li><%= link_to 'ログアウト', destroy_user_session_path, class: "user-button", method: :delete %></li>
      <% end %>
    </ul>
    <div class="to-seller">
      <div class="to-seller-info">
        販売者様はこちら
      </div>
      <div>
        >><%= link_to '販売者専用ページ', new_seller_session_path , class: "to-seller-button" %>
      </div>
    </div>
  </div>



</header>

app/views/shared/_header2.html.erb
<header class="header2">
  <div class="logo2">
    <%= link_to image_tag("logo1.PNG", class:"ecshop-icon2"), items_path %>
  </div>
</header>

app/views/shared/_header3.html.erb
<header class="header1">
  <div class="logo1">
    <%= link_to image_tag("logo1.PNG", class:"ecshop-icon1"), top_managements_path %>
  </div>
  <div class="for-seller">
    〜販売者様専用ページ〜
  </div>
  <div class="nav1">
    <ul class="buttons">
      <li><%= link_to '販売者ログアウト', destroy_seller_session_path, class: "seller-button", method: :delete %></li>
    </ul>
  </div>
</header>

app/views/shared/_header4.html.erb
<header class="header2">
  <div class="logo2">
    <%= link_to image_tag("logo1.PNG", class:"ecshop-icon2"), top_managements_path %>
  </div>
</header>

app/views/shared/_item_middle.html.erb
<li class="item-list">
  <div class="item-image">
    <%= link_to image_tag(item.image, class:"item-index-image"), item_path(item.id) %>
    <div class="hearts">
      <% if user_signed_in? && FavoriteItem.exists?(user_id: "#{current_user.id}", item_id: item.id) && FavoriteItem.find_by(user_id: "#{current_user.id}", item_id: item.id).checked%>
      <div class="pink-heart" data-id=<%= item.id%> >
        <%= image_tag "ハート.png", class:"item-middle-heart-image"%>
      </div>
      <% else %>
      <div class="pink-heart" data-id=<%= item.id%> style="filter: brightness(50%);">
        <%= image_tag "ハート.png", class:"item-middle-heart-image" %>
      </div>
      <% end %>
    </div>
  </div>

  <div class="item-index-info">
    <b><%= link_to item.name,item_path(item.id), class: "item-index-name" %></b>
    <div class="item-index-seller">
      <%= link_to item.seller.store_name,seller_path(item.seller.id), class: "item-index-seller" %>
    </div>
    <div class="item-index-3rd-row">
      <ul class="item-index-tags">
        <li class=item-index-tag><%= item.tag1 %></li>
        <li class=item-index-tag><%= item.tag2 %></li>
        <li class=item-index-tag><%= item.tag3 %></li>
        <li class=item-index-tag><%= item.tag4 %></li>
        <li class=item-index-tag><%= item.tag5 %></li>
      </ul>
      <div class="item-index-evaluation">評価
        <span style="font-size:15pt">
          <% if Review.exists?(item_id: "#{item.id}") %>
          <%= Review.where(item_id: "#{item.id}").average(:evaluation).round(1) %>
          <% else %>
          <span style="font-size:8pt">未評価</span>
          <% end %>
        </span> / 5
      </div>
    </div>
    <div class="item-index-4th-row">
      <div class="item-index-stock">在庫 <span style="font-size:15pt"><%= item.stock.count %></span> 個</div>
      <div class="item-index-price"><%= item.price %> <span style="font-size:10pt">円</span></div>
    </div>
  </div>
</li>

app/views/shared/_item_seller_middle.html.erb
<li class="item-list">
  <div>
    <%= image_tag item.image, class:"item-index-image" %>
  </div>
  <div class="item-index-info">
    <b>
      <div class="item-index-name"><%= item.name %></div>
    </b>
    <div class="item-index-seller">
      <div class="item-index-seller"><%=  item.seller.store_name %></div>
    </div>
    <div class="item-index-3rd-row">
      <ul class="item-index-tags">
        <li class=item-index-tag><%= item.tag1 %></li>
        <li class=item-index-tag><%= item.tag2 %></li>
        <li class=item-index-tag><%= item.tag3 %></li>
        <li class=item-index-tag><%= item.tag4 %></li>
        <li class=item-index-tag><%= item.tag5 %></li>
      </ul>
      <div class="item-index-evaluation">評価
        <span style="font-size:15pt">
          <% if Review.exists?(item_id: "#{item.id}") %>
          <%= Review.where(item_id: "#{item.id}").average(:evaluation).round(1) %>
          <% else %>
          <span style="font-size:8pt">未評価</span>
          <% end %>
        </span> / 5
      </div>
    </div>
    <div class="item-index-4th-row">
      <div class="item-index-stock">在庫 <span style="font-size:15pt"><%= item.stock.count %></span> 個</div>
      <div class="item-index-price"><%= item.price %> <span style="font-size:10pt">円</span></div>
    </div>
  </div>
</li>

app/views/shared/_item_seller_small.html.erb
<div class="item-seller-small">
  <div class="item--seller-small-image">
    <%= image_tag @item.image ,class: "item-seller-small-image" %>
  </div>
  <div class="item-seller-small-info">
    <div class=item-seller-small-name><%= @item.name %></div>
    <div class="item-seller-small-row2">
      <div class="item-seller-small-seller"><%= @item.seller.store_name %></div>
      <div class="item-seller-small-stock">在庫 <%= @item.stock.count %> セット</div>
    </div>
  </div>
</div>

app/views/shared/_item_small.html.erb
<div class="item-seller-small">
  <div class="item-seller-small-image">
    <%= image_tag @item.image ,class: "item-seller-small-image" %>
    <div class="hearts">
      <% if FavoriteItem.exists?(user_id: "#{current_user.id}", item_id: @item.id) && FavoriteItem.find_by(user_id: "#{current_user.id}", item_id: @item.id).checked%>
      <div class="pink-heart" data-id=<%= @item.id%>>
        <%= image_tag "ハート.png", class:"item-middle-heart-image-small"%>
      </div>
      <% else %>
      <div class="pink-heart" data-id=<%= @item.id%> style="filter: brightness(50%);">
        <%= image_tag "ハート.png", class:"item-middle-heart-image-small" %>
      </div>
      <% end %>
    </div>
  </div>
  <div class="item-seller-small-info">
    <div class=item-seller-small-name><%= link_to @item.name, item_path(@item.id),class:"edit-button-link"%></div>
    <div class="item-seller-small-row2">
      <div class="item-seller-small-seller">
        <%= link_to @item.seller.store_name, seller_path(@item.seller.id),class:"edit-button-link"%></div>
      <div class="item-seller-small-stock">在庫 <%= @item.stock.count %> セット</div>
    </div>
  </div>
</div>

app/views/shared/_searchbar.html.erb
<div class="searchbar">
  <%= form_with(url: search_items_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: " 商品名 料理名 食材 など", class: "search-input" %>
  <%= form.submit "検索する", class: "search-btn" %>
  <% end %>
</div>

app/views/shared/_seller_small.html.erb
<div class="item-seller-small">
  <div class="item-seller-small-image">
    <%= image_tag @seller.store.image ,class: "item-seller-small-image" %>
    <div class="hearts">
      <% if user_signed_in? && FavoriteSeller.exists?(user_id: "#{current_user.id}", seller_id: @seller.id) && FavoriteSeller.find_by(user_id: "#{current_user.id}", seller_id: @seller.id).checked%>
      <div class="seller-pink-heart" data-id=<%= @seller.id%>>
        <%= image_tag "ハート.png", class:"item-middle-heart-image-small"%>
      </div>
      <% else %>
      <div class="seller-pink-heart" data-id=<%= @seller.id%> style="filter: brightness(50%);">
        <%= image_tag "ハート.png", class:"item-middle-heart-image-small" %>
      </div>
      <% end %>
    </div>
  </div>
  <div class="item-seller-small-info">
    <div class=item-seller-small-name>
      <%= link_to "#{@seller.store_name}",seller_path(@seller.id),class:"edit-button-link"%>
      <span class="seller-show-category"><%= @seller.store.shopcategory.name %></span>
    </div>
    <div class="seller-small-row2">
      <div class="seller-small-show-row2">
        〒 <%= @seller.store.zip_code %> <%= @seller.store.address %>
      </div>
      <div class="seller-small-show-row2">
        Tel <%= @seller.store.phone_number %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sidebar2.html.erb
<div class="sidebar1">
  <div class="side2-user-info">
    <div class="side2-user-name">
      ようこそ
      <br><%= current_seller.store_name %> 様
    </div>
  </div>

  <ul class="side-user-lists">

    <li class="side-user-list">
      <%= link_to '>> 出品管理', items_managements_path, class: "side-user-list-button" %>
    </li>
    <li class="side-user-list">
      <%= link_to '>> 購入された商品',  orders_managements_path, class: "side-user-list-button" %>
    </li>
    <li class="side-user-list">
      <%= link_to '>> お客様とのメッセージ', roomindex_managements_path, class: "side-user-list-button" %>
    </li>
    <li class="side-user-list">
      <%= link_to '>> 販売店情報編集', edit_seller_registration_path, class: "side-user-list-button" %>
    </li>
  </ul>
</div>