config/routes.rb
Rails.application.routes.draw do

  root to: 'app#top'
  
  resources :app do
    collection do
      get 'top'
    end
  end

  resources :managements do
    collection do
      get 'top'
      get 'items'
      get 'orders'
      get 'roomindex'
      get 'messageindex'
      post 'messagecreate'
      post 'roomcreate'
    end
  end

  resources :items do
    resources :stocks, only: [:edit, :update]
    collection do
      get 'search'
    end
  end

  get 'item/:id', to: 'items#checked'
  get 'seller/:id', to: 'sellers#checked'

  resources :orders, only: [:new, :create, :index] do
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :rooms, only:[:create, :index] do
    resources :messages, only: [:create, :index]
  end

  resources :favoriteitems, only: :index
  resources :favoritesellers, only: :index

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  devise_for :sellers, controllers: {
    sessions:      'sellers/sessions',
    passwords:     'sellers/passwords',
    registrations: 'sellers/registrations'
  }


  resources :sellers, only: :show

  resources :users do
    resources :charges, only: [:new, :create, :edit, :update]
  end

end

app/models/item.rb
class Item < ApplicationRecord


  with_options presence: true do
    validates :name
    validates :information
    validates :image
    
    with_options numericality: { with: /\A[0-9]+\z/, message: "must be Half-width numbers"} do
      validates :price, numericality: { :greater_than_or_equal_to => 300 , :less_than_or_equal_to => 9999999 , message:"must be 300~9999999" }
    end

    with_options numericality: { other_than: 0 , message: "must be selected"}  do
      validates :prefecture_id
      validates :ship_day_id
      validates :ship_type_id
    end
  end

  with_options length: { maximum: 5, message: "must be 5 digits or less" }  do
    validates :tag1
    validates :tag2
    validates :tag3
    validates :tag4
    validates :tag5
  end

  belongs_to :seller
  has_one :stock
  has_one_attached :image
  has_many :orders
  has_many :reviews
  has_many :favorite_items

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture
  belongs_to :ship_day
  belongs_to :ship_type
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :authenticate_seller!, only: [:new, :create, :edit, :update]
  
  def index
    @items = Item.includes(:stock,:seller).order('created_at DESC')
  end

  def show
    @item = Item.find(params[:id])
    @reviews = Review.where(item_id: @item.id)
  end

  def new
    @new_item = NewItem.new
  end

  def create
    @new_item = NewItem.new(item_params)
    if @new_item.allergies != nil 
      @new_item.allergies = @new_item.allergies.join("・")
    else
      @new_item.allergies = "" 
    end
    if @new_item.valid?
      @new_item.save
      redirect_to top_managements_path, notice: "新規出品が完了しました"
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if params[:item][:allergies] != nil
      params[:item][:allergies] = params[:item][:allergies].join("・")
    else
      params[:item][:allergies] = ""
    end
    if @item.update(edit_item_params)
      redirect_to items_managements_path, notice: "編集が完了しました"
    else
      render :edit
    end
  end

  def checked
    if FavoriteItem.exists?(user_id: "#{current_user.id}", item_id: params[:id])
      favoriteitem = FavoriteItem.find_by(user_id: "#{current_user.id}", item_id: params[:id])
      if favoriteitem.checked
        favoriteitem.update(checked: false)
      else
        favoriteitem.update(checked: true)
      end
    else
      favoriteitem = FavoriteItem.create(user_id: "#{current_user.id}", item_id: params[:id], checked: true)
    end
    favoriteitem = FavoriteItem.find_by(user_id: "#{current_user.id}", item_id: params[:id])
    render json: { heart: favoriteitem }
  end

  def search
    @search = params[:keyword]
    if @search != ""
      @items = Item.where(["name LIKE(?) OR information LIKE(?) OR tag1 LIKE(?) OR tag2 LIKE(?) OR tag3 LIKE(?) OR tag4 LIKE(?) OR tag5 LIKE(?)", "%#{@search}%", "%#{@search}%", "%#{@search}%", "%#{@search}%", "%#{@search}%", "%#{@search}%", "%#{@search}%"]).order('created_at DESC')
    else
      @items = Item.all.order('created_at DESC')
    end
  end
  


  private

  def item_params
    params.require(:new_item).permit(:image, :name, :price, :information, :tag1, :tag2, :tag3, :tag4, :tag5, :prefecture_id, :ship_day_id, :ship_type_id, :count, allergies:[]).merge(seller_id: current_seller.id)
  end

  def edit_item_params
    params.require(:item).permit(:image, :name, :price, :information, :tag1, :tag2, :tag3, :tag4, :tag5, :prefecture_id, :ship_day_id, :ship_type_id, :allergies).merge(seller_id: current_seller.id)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<%= render "shared/header3" %>

<div class="body-include-sidebar">

  <%= render "shared/sidebar2" %>

  <div class="main-body">

    <%= form_with model: @item, url: item_path, class: 'registration-main', local: true do |f| %>

    <div class='form2-wrap'>
      <div class='form-header'>
        <h1 class='form-header-text'>
          商品編集
        </h1>
      </div>

      <%= render 'shared/error_messages', model: f.object %>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">商品名</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :name, class:"input-default", placeholder: "例) 簡単！カルボナーラセット"%>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">商品画像</label>
          <span class="indispensable">必須</span>
        </div>
        <div class="click-upload">
          <%= f.file_field :image, class:"seller-image" %>
        </div>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">商品情報</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :information, class:"input-seller-info", placeholder: "例) 生クリームが無くても牛乳で手軽に作れるカルボナーラ！特製チーズセットをご用意！卵と牛乳を用意していただくだけで作れます！" %>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">タグ(5つまで設定できます)</label>
          <p class='info-text'>※各最大5文字</p>
        </div>
        <%= f.text_field :tag1, class:"input-default", placeholder:"パスタ"%>
        <%= f.text_field :tag2, class:"input-default", placeholder:"イタリアン"%>
        <%= f.text_field :tag3, class:"input-default", placeholder:"チーズ"%>
        <%= f.text_field :tag4, class:"input-default", placeholder:""%>
        <%= f.text_field :tag5, class:"input-default", placeholder:""%>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">発送する地域</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">発送までの日数</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:ship_day_id, ShipDay.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">発送の種類</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:ship_type_id, ShipType.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">アレルゲン表示(特定原材料7品目)</label>
        </div>
        <div class="allergies-check-box">
          <% ["卵","乳","小麦","そば","落花生","えび","かに"].each.with_index do |allergy| %>
          <%= f.check_box :allergies, {multiple: true}, allergy, nil %>
          <%= allergy %>
          <% end %>
        </div>
        <p class='info-text'>※その他のアレルゲンについては"商品情報"に記載してください</p>
      </div>

      <div class="form-group">
        <div class="sell-price">
          <label class="form-text">商品価格</label><span class="indispensable">必須</span>
          <p class='info-text'>※価格は¥300~999999の範囲で設定してください</p>
          <div class="price-content">
            <div class="price-text">
              <span>価格</span>
            </div>
            <span class="sell-yen">¥</span>
            <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）980" %>
          </div>
          <div class="price-content">
            <span>販売手数料 (5%)</span>
            <span>
              <span id='add-tax-price'></span>円
            </span>
          </div>
          <div class="price-content">
            <span>販売利益</span>
            <span>
              <span id='profit'></span>円
          </div>
          </span>
        </div>
      </div>


      <br>
        <div class="form-group">
          <p class='form-info-text'>
            「編集完了」のボタンを押すことにより、
            <span class="seller-new-kiyaku">利用規約</span>に同意したものとみなします
          </p>
        </div>
        <br>
        <div class='register-btn'>
          <%= f.submit "編集完了" ,class:"register-red-btn" %>
        </div>
        <br>



      <% end %>

    </div>

  </div>
</div>

<%= render "shared/footer2" %>

app/views/items/index.html.erb
<%= render "shared/header1" %>

<div class="body-include-sidebar">

  <%= render "shared/sidebar1" %>

  <div class="main-body">


    <div class="notice"><%= notice %></div>


    <%= render "shared/searchbar" %>

    <div class="main-body-body">

      <div class="main-body-title">
        <span style="color:#51456A">新着商品一覧</span>
      </div>

      <ul class=item-lists>

        <% @items.each do |item| %>
        <%= render partial: "shared/item_middle", locals: {item: item }%>
        <% end %>

      </ul>
    </div>

  </div>

</div>

<%= render "shared/footer1" %>

app/views/items/new.html.erb
<%= render "shared/header3" %>

<div class="body-include-sidebar">

  <%= render "shared/sidebar2" %>

  <div class="main-body">

    <%= form_with model: @new_item, url: items_path, class: 'registration-main', local: true do |f| %>

    <div class='form2-wrap'>
      <div class='form-header'>
        <h1 class='form-header-text'>
          商品新規登録
        </h1>
      </div>

      <%= render 'shared/error_messages', model: f.object %>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">商品名</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :name, class:"input-default", placeholder: "例) 簡単！カルボナーラセット"%>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">商品画像</label>
          <span class="indispensable">必須</span>
        </div>
        <div class="click-upload">
          <%= f.file_field :image, class:"seller-image" %>
        </div>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">商品情報</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :information, class:"input-seller-info", placeholder: "例) 生クリームが無くても牛乳で手軽に作れるカルボナーラ！特製チーズセットをご用意！卵と牛乳を用意していただくだけで作れます！" %>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">タグ(5つまで設定できます)</label>
          <p class='info-text'>※各最大5文字</p>
        </div>
        <%= f.text_field :tag1, class:"input-default", placeholder:"パスタ"%>
        <%= f.text_field :tag2, class:"input-default", placeholder:"イタリアン"%>
        <%= f.text_field :tag3, class:"input-default", placeholder:"チーズ"%>
        <%= f.text_field :tag4, class:"input-default", placeholder:""%>
        <%= f.text_field :tag5, class:"input-default", placeholder:""%>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">発送する地域</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">発送までの日数</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:ship_day_id, ShipDay.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">発送の種類</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:ship_type_id, ShipType.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">アレルゲン表示(特定原材料7品目)</label>
        </div>
        <div class="allergies-check-box">
          <% ["卵","乳","小麦","そば","落花生","えび","かに"].each.with_index do |allergy| %>
          <%= f.check_box :allergies, {multiple: true}, allergy, nil %>
          <%= allergy %>
          <% end %>
        </div>
        <p class='info-text'>※その他のアレルゲンについては"商品情報"に記載してください</p>
      </div>

      <div class="form-group">
        <div class="sell-price">
          <label class="form-text">商品価格</label><span class="indispensable">必須</span>
          <p class='info-text'>※価格は¥300~999999の範囲で設定してください</p>
          <p class='info-text'>※価格は半角数字で入力してください</p>
          <div class="price-content">
            <div class="price-text">
              <span>価格</span>
            </div>
            <span class="sell-yen">¥</span>
            <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）980" %>
          </div>
          <div class="price-content">
            <span>販売手数料 (5%)</span>
            <span>
              <span id='add-tax-price'></span>円
            </span>
          </div>
          <div class="price-content">
            <span>販売利益</span>
            <span>
              <span id='profit'></span>円
          </div>
          </span>
        </div>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">商品在庫数</label>
          <span class="indispensable">必須</span>

        </div>
        <div>
          <%= f.text_field :count, class:"input-default-stock"%> セット
        </div>
        <p class='info-text'>※在庫数は0~10000の範囲で設定してください</p>
        <p class='info-text'>※在庫数は半角数字で入力してください</p>
        <p class='info-text'>※出品管理画面より編集ができます</p>
      </div>


      <br>
      <div class="form-group">
        <p class='form-info-text'>
          「登録完了」のボタンを押すことにより、
          <span class="seller-new-kiyaku">利用規約</span>に同意したものとみなします
        </p>
      </div>
      <br>
      <div class='register-btn'>
        <%= f.submit "登録完了" ,class:"register-red-btn" %>
      </div>
      <br>



      <% end %>

    </div>

  </div>
</div>

<%= render "shared/footer2" %>

app/views/items/search.html.erb
<%= render "shared/header1" %>

<div class="body-include-sidebar">

  <%= render "shared/sidebar1" %>

  <div class="main-body">

    <%= render "shared/searchbar" %>

    <div class="main-body-body">

      <div class="main-body-title">
        <span style="color:#51456A"><%= @search %>の検索結果</span>
      </div>

      <ul class=item-lists>

        <% @items.each do |item| %>
        <%= render partial: "shared/item_middle", locals: {item: item }%>
        <% end %>

      </ul>
    </div>

  </div>

</div>

<%= render "shared/footer1" %>

app/views/items/show.html.erb
<%= render "shared/header1" %>

<div class="body-include-sidebar">

  <%= render "shared/sidebar1" %>

  <div class="main-body">

    <%= render "shared/searchbar" %>

    <div class="main-body-body">

      <div class="main-body-title">
        <span style="color:#51456A">商品詳細</span>
      </div>

      <div class="item-show-up">
        <div class="item-show-images">
          <%= image_tag @item.image ,class: "item-show-image" %>
          <div class="hearts">
            <% if user_signed_in? && FavoriteItem.exists?(user_id: "#{current_user.id}", item_id: @item.id) && FavoriteItem.find_by(user_id: "#{current_user.id}", item_id: @item.id).checked%>
            <div class="pink-heart" data-id=<%= @item.id%>>
              <%= image_tag "ハート.png", class:"item-middle-heart-image"%>
            </div>
            <% else %>
            <div class="pink-heart" data-id=<%= @item.id%> style="filter: brightness(50%);">
              <%= image_tag "ハート.png", class:"item-middle-heart-image" %>
            </div>
            <% end %>
          </div>
        </div>
        <div class="item-show-info">
          <div class="item-show-name"><b><%= @item.name %></b></div>
          <div class="item-show-row2">
            <ul class="item-show-tags">
              <li class=item-show-tag><%= @item.tag1 %></li>
              <li class=item-show-tag><%= @item.tag2 %></li>
              <li class=item-show-tag><%= @item.tag3 %></li>
              <li class=item-show-tag><%= @item.tag4 %></li>
              <li class=item-show-tag><%= @item.tag5 %></li>
            </ul>
            <div class="item-show-seller">
              <%= link_to @item.seller.store_name,seller_path(@item.seller.id), class: "item-show-seller" %>
            </div>
          </div>
          <div class="item-show-text">
            <%= @item.information %>
          </div>
          <div class="item-show-evaluation">評価
            <span style="font-size:18pt">
              <% if Review.exists?(item_id: "#{@item.id}") %>
              <%= Review.where(item_id: "#{@item.id}").average(:evaluation).round(1) %>
              <% else %>
              <span style="font-size:8pt">未評価</span>
              <% end %>
            </span> / 5
          </div>
          <div class="item-show-allergies">含まれるアレルギー(7品目) <%= @item.allergies %></div>
        </div>
      </div>

      <div class="item-show-down">
        <div class="item-show-ship">
          <span class="ship-text-info" , style="font-size:16pt">発送について</span>
          <table class="item-show-ship">
            <tbody>
              <tr>
                <th class="item-show-ship-prefecture">発送元の地域</th>
                <td class="item-show-ship-prefecture-value"><%= @item.prefecture.name %></td>
              </tr>
              <tr>
                <th class="item-show-ship-day">発送までの日数</th>
                <td class="item-show-ship-day-value"><%= @item.ship_day.name %></td>
              </tr>
              <tr>
                <th class="item-show-ship-typ">発送方法</th>
                <td class="item-show-ship-typ-value"><%= @item.ship_type.name %></td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="item-show-stock">在庫 <span style="font-size:20pt"><%= @item.stock.count %></span> 個</div>
        <div class="item-show-price"><%= @item.price %> 円 <span style="font-size:10pt">(税込)</span></div>
        <%= link_to '購入へ進む', new_order_path(@item.id), class: "show-order-button" %>
      </div>
      <br>
      <br>


      <div class="item-show-review-title">
        商品レビュー
      </div>
      <ul class=item-show-reviews>


        <% if Review.exists?(item_id: "#{@item.id}") %>
        <% @reviews.each do |review| %>
        <li class=item-show-review>
          <div class="item-show-review-up">
            <div class="item-show-review-name"><b><%= review.user.nickname %></b> さん</div>
            <div class="item-show-review-evaluation">評価 <span style="font-size:18pt"><%= review.evaluation %></span> / 5
            </div>
            <div class="item-show-review-date">購入日<%= review.order.created_at.to_s(:date_jp) %></div>
          </div>
          <div class="item-show-review-text"><%= review.text %></div>
        </li>
        <% end %>
        <% else %>
        <div style="color:#51456A">レビューはありません</div>
        <% end %>

      </ul>

    </div>

  </div>

</div>

<%= render "shared/footer1" %>