config/routes.rb
Rails.application.routes.draw do

  root to: 'app#top'
  
  resources :app do
    collection do
      get 'top'
    end
  end

  resources :managements do
    collection do
      get 'top'
      get 'items'
      get 'orders'
      get 'roomindex'
      get 'messageindex'
      post 'messagecreate'
      post 'roomcreate'
    end
  end

  resources :items do
    resources :stocks, only: [:edit, :update]
    collection do
      get 'search'
    end
  end

  get 'item/:id', to: 'items#checked'
  get 'seller/:id', to: 'sellers#checked'

  resources :orders, only: [:new, :create, :index] do
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :rooms, only:[:create, :index] do
    resources :messages, only: [:create, :index]
  end

  resources :favoriteitems, only: :index
  resources :favoritesellers, only: :index

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  devise_for :sellers, controllers: {
    sessions:      'sellers/sessions',
    passwords:     'sellers/passwords',
    registrations: 'sellers/registrations'
  }


  resources :sellers, only: :show

  resources :users do
    resources :charges, only: [:new, :create, :edit, :update]
  end

end

app/models/charge.rb
class Charge < ApplicationRecord
  attr_accessor :token

  validates :pay, presence: true, numericality: { with: /\A[0-9]+\z/, message: "must be Half-width numbers"}
  validates :token, presence: true
  belongs_to :user
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update]

  def new
    @charge = Charge.new
  end
  
  def create
    if charge_params[:pay].to_i >= 50 
      @charge = Charge.new(charge_params)
      if @charge.valid?
        pay_new_charege
        @charge.save
        redirect_to items_path, notice: "チャージが完了しました"
      else
        flash.now[:alert] = "クレジットカード情報を確認してください"
        render action: :new
      end
    else
      flash.now[:alert] = "¥50以上のチャージをしてください"
      @charge = Charge.new
      render :new
    end
  end

  def edit
    @charge = Charge.find(current_user.charge.id)
  end

  def update
    @charge = Charge.find(params[:id])
    now_charge = @charge.pay
    new_charge = params[:charge][:pay].to_i
    if new_charge >= 50 
      params[:charge][:pay] = now_charge + new_charge
      if @charge.update(charge_params) &&  pay_edit_charge(new_charge)
        redirect_to items_path, notice: "チャージが完了しました"
      else
        flash.now[:alert] = "クレジットカード情報を確認してください"
        render :edit
      end
    else
      flash.now[:alert] = "¥50以上のチャージをしてください"
      render :edit
    end
  end

  private

  def charge_params
    params.require(:charge).permit(:pay).merge(user_id: current_user.id, token: params[:token]) 
  end

  def pay_new_charege
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
      Payjp::Charge.create(
        amount: charge_params[:pay],
        card: charge_params[:token],
        currency: 'jpy'
      )
  end

  def pay_edit_charge(new_charge)
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
      Payjp::Charge.create(
        amount: new_charge,
        card: charge_params[:token],
        currency: 'jpy'
      )
  end
  
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/edit.html.erb
<%= render "shared/header1" %>

<div class="body-include-sidebar">

  <%= render "shared/sidebar1" %>

  <div class="main-body">
    <div class="main-body-body">

      <%= form_with model:@charge, url: user_charge_path, class: 'charge-pay',id: 'charge-pay', local: true do |f| %>

      <div class='form2-wrap'>
        <div class='form-header'>
          <h1 class='form-header-text'>
            残高チャージ
          </h1>
        </div>

        <div class="alert"><%= alert %></div>
        
        <div class='credit-card-form'>
          
          <div class="form-group">
          <h1 class='info-input-haedline'>
            クレジットカード情報入力
          </h1>
            <div class='form-text-wrap'>
              <label class="form-text">カード情報</label>
              <span class="indispensable">必須</span>
            </div>
            <%= f.text_field :number, class:"input-default", id:"card-number", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
            <div class='available-card'>
              <%= image_tag 'card-visa.gif', class: 'card-logo'%>
              <%= image_tag 'card-mastercard.gif', class: 'card-logo'%>
              <%= image_tag 'card-jcb.gif', class: 'card-logo'%>
              <%= image_tag 'card-amex.gif', class: 'card-logo'%>
            </div>
          </div>
          <div class="form-group">
            <div class='form-text-wrap'>
              <label class="form-text">有効期限</label>
              <span class="indispensable">必須</span>
            </div>
            <div class='input-expiration-date-wrap'>
              <%= f.text_area :exp_month, class:"input-expiration-date", id:"card-exp-month", placeholder:"例)3" %>
              <p>月</p>
              <%= f.text_area :exp_year, class:"input-expiration-date", id:"card-exp-year", placeholder:"例)23" %>
              <p>年</p>
            </div>
          </div>
          <div class="form-group">
            <div class='form-text-wrap'>
              <label class="form-text">セキュリティコード</label>
              <span class="indispensable">必須</span>
            </div>
            <%= f.text_field :cvc, class:"input-default", id:"card-cvc", placeholder:"カード背面4桁もしくは3桁の番号", maxlength:"4" %>
          </div>
        </div>

        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">チャージ額</label>
            <span class="indispensable">必須</span>
          </div>
          <div class="charge-form">
            <span style="font-size:15pt">¥</span>
            <%= f.text_field :pay, class:"input-charge-default", id:"input-charge", placeholder: "50以上の半角数字で入力してください",value: ""%>
          </div>
          <div class="charge-changes">
            <div class="charge-change">
              <div class="charge-change-text">現在の残高</div>
              <div class="charge-change-value" >¥ <span id="now-charge"><%= current_user.charge.pay %></span></div>
            </div>
            <span style="font-size:15pt">→</span>
            <div class="charge-change">
              <div class="charge-change-text">チャージ後の残高</div>
              <div class="charge-change-value">¥ <span id="new-charge"></span></div>
            </div>
          </div>
        </div>
        <br>
        <div class='register-btn'>
          <%= f.submit "チャージ" ,class:"register-red-btn" %>
        </div>
        <br>


        <% end %>

      </div>

    </div>
  </div>

</div>

<%= render "shared/footer2" %>

app/views/charges/new.html.erb
<%= render "shared/header1" %>

<div class="body-include-sidebar">

  <%= render "shared/sidebar1" %>

  <div class="main-body">
    <div class="main-body-body">

      <%= form_with model:@charge, url: user_charges_path, class: 'charge-pay',id: 'charge-pay', local: true do |f| %>

      <div class='form2-wrap'>
        <div class='form-header'>
          <h1 class='form-header-text'>
            残高チャージ
          </h1>
        </div>

        <div class="alert"><%= alert %></div>

        <div class='credit-card-form'>
          
          <div class="form-group">
          <h1 class='info-input-haedline'>
            クレジットカード情報入力
          </h1>
            <div class='form-text-wrap'>
              <label class="form-text">カード情報</label>
              <span class="indispensable">必須</span>
            </div>
            <%= f.text_field :number, class:"input-default", id:"card-number", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
            <div class='available-card'>
              <%= image_tag 'card-visa.gif', class: 'card-logo'%>
              <%= image_tag 'card-mastercard.gif', class: 'card-logo'%>
              <%= image_tag 'card-jcb.gif', class: 'card-logo'%>
              <%= image_tag 'card-amex.gif', class: 'card-logo'%>
            </div>
          </div>
          <div class="form-group">
            <div class='form-text-wrap'>
              <label class="form-text">有効期限</label>
              <span class="indispensable">必須</span>
            </div>
            <div class='input-expiration-date-wrap'>
              <%= f.text_area :exp_month, class:"input-expiration-date", id:"card-exp-month", placeholder:"例)3" %>
              <p>月</p>
              <%= f.text_area :exp_year, class:"input-expiration-date", id:"card-exp-year", placeholder:"例)23" %>
              <p>年</p>
            </div>
          </div>
          <div class="form-group">
            <div class='form-text-wrap'>
              <label class="form-text">セキュリティコード</label>
              <span class="indispensable">必須</span>
            </div>
            <%= f.text_field :cvc, class:"input-default", id:"card-cvc", placeholder:"カード背面4桁もしくは3桁の番号", maxlength:"4" %>
          </div>
        </div>

        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">チャージ額</label>
            <span class="indispensable">必須</span>
          </div>
          <div class="charge-form">
            <span style="font-size:15pt">¥</span>
            <%= f.text_field :pay, class:"input-charge-default", id:"input-charge", placeholder: "50以上の半角数字で入力してください"%>
          </div>
          <div class="charge-changes">
            <div class="charge-change">
              <div class="charge-change-text">現在の残高</div>
              <div class="charge-change-value">¥ <span id="now-charge">0</span></div>
            </div>
            <span style="font-size:15pt">→</span>
            <div class="charge-change">
              <div class="charge-change-text">チャージ後の残高</div>
              <div class="charge-change-value">¥ <span id="new-charge"></span></div>
            </div>
          </div>
        </div>
        <br>
        <div class='register-btn'>
          <%= f.submit "チャージ" ,class:"register-red-btn" %>
        </div>
        <br>


        <% end %>

      </div>

    </div>
  </div>

</div>

<%= render "shared/footer2" %>