config/routes.rb
Rails.application.routes.draw do

  root to: 'app#top'
  
  resources :app do
    collection do
      get 'top'
    end
  end

  resources :managements do
    collection do
      get 'top'
      get 'items'
      get 'orders'
      get 'roomindex'
      get 'messageindex'
      post 'messagecreate'
      post 'roomcreate'
    end
  end

  resources :items do
    resources :stocks, only: [:edit, :update]
    collection do
      get 'search'
    end
  end

  get 'item/:id', to: 'items#checked'
  get 'seller/:id', to: 'sellers#checked'

  resources :orders, only: [:new, :create, :index] do
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :rooms, only:[:create, :index] do
    resources :messages, only: [:create, :index]
  end

  resources :favoriteitems, only: :index
  resources :favoritesellers, only: :index

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  devise_for :sellers, controllers: {
    sessions:      'sellers/sessions',
    passwords:     'sellers/passwords',
    registrations: 'sellers/registrations'
  }


  resources :sellers, only: :show

  resources :users do
    resources :charges, only: [:new, :create, :edit, :update]
  end

end

app/controllers/managements_controller.rb
class ManagementsController < ApplicationController
  before_action :authenticate_seller!


  def top
    @items = current_seller.items.order('created_at DESC')
  end

  def items
    @items = current_seller.items.order('created_at DESC')
  end

  def orders
    items = current_seller.items
    @orders = Order.where(item_id: items.ids).order('created_at DESC')
  end

  def roomindex
    @rooms = current_seller.rooms
  end

  def messageindex
    @room = Room.find(params[:format])
    @messages = @room.messages
    @message = Message.new
    set_item_name
  end

  def messagecreate
    @room = Room.find(params[:format])
    @message = Message.new(message_params)
    if @message.valid?
      @message.save
      redirect_to  messageindex_managements_path(@room.id), notice: "メッセージを送信しました"
    else
      @messages = Message.where(params[:format])
      set_item_name
      redirect_to messageindex_managements_path(@room.id), notice: "メッセージ送信に失敗しました。内容を確認してください"
    end
  end

  def roomcreate
    if Room.exists?(seller_id: "#{current_seller.id}", user_id: params[:format])
      @room = Room.find_by(seller_id: "#{current_seller.id}", user_id: params[:format])
      redirect_to messageindex_managements_path(@room.id)
    else
      @room = Room.create(seller_id: current_seller.id, user_id: params[:format])
      redirect_to messageindex_managements_path(@room.id)
    end
  end

  private

  def message_params
    params.require(:message).permit(:item_name, :message).merge(room_id: @room.id, whom: current_seller.store_name )
  end

  def set_item_name
    @items = Item.where(seller_id: @room.seller.id)
    @item_name = []
    @items.each do |item|
      @item_name.push(item.name)
    end
    @item_name.push("その他")
  end
end

app/helpers/managements_helper.rb
module ManagementsHelper
end

app/views/managements/items.html.erb
<%= render "shared/header3" %>

<div class="body-include-sidebar">

  <%= render "shared/sidebar2" %>

  <div class="main-body">

    <div class="notice"><%= notice %></div>
    <div class="main-body-body">

      <div class="main-body-title">
        <span style="color:#51456A">出品一覧</span>
      </div>
      <div>新規出品はこちらから→<%= link_to '新規出品', new_item_path,class:"new-item-button-link"%></div>
      <br>
      <ul class="seller-items">

        <% @items.each do |item| %>
        <% @item = item %>
        <li class="seller-item">
          <%= render partial: "shared/item_seller_small"%>
          <ul class="edit-buttons">
            <li class="edit-button">
              <%= link_to '在庫数編集',edit_item_stock_path(item.id,item.stock.id),class:"edit-button-link"%></li>
            <li class="edit-button"><%= link_to '商品編集', edit_item_path(item.id) ,class:"edit-button-link"%></li>
            <%# <li class="edit-button"><%= link_to '商品削除', item_path(item.id), class:"edit-button-link", method: :delete </li>  %>
          </ul>
        </li>
        <% end %>

      </ul>

    </div>

  </div>
</div>

</div>

<%= render "shared/footer2" %>

app/views/managements/messageindex.html.erb
<%= render "shared/header3" %>

<div class="body-include-sidebar">

  <%= render "shared/sidebar2" %>

  <div class="main-body">

    <div class="notice"><%= notice %></div>

    <div class="main-body-body">

      <div class="main-body-title">
        <span style="color:#51456A"><%= @room.user.profile.last_name %><%= @room.user.profile.first_name %>
          様とのメッセージ</span>
      </div>

      <ul class=messages>

        <% @messages.each do |message| %>
        <li class=message>
          <div class="message-up">
            <div class="message-name"><b><%= message.whom %> 様</b></div>
            <div class="message-time"><%= message.created_at.to_s(:datetime_jp) %></div>
          </div>
          <div class="message-item-name"><%= message.item_name %></div>
          <div class="message-text"><%= message.message %></div>
        </li>
        <% end %>

      </ul>


      <%= form_with model: @message, url: messagecreate_managements_path(@room.id), class: 'message-form', local: true do |f| %>
      <div class="message-form-input">
        <span style="font-size:15pt">新規メッセージ</span>
        <div class="message-form-row2">
          <%= f.select :item_name, @item_name, {include_blank: '--'}, class: 'message-item-select' %>について
        </div>
        <%= f.text_area :message, class: 'message-form-text', placeholder: 'メッセージを入力' %>
        <%= f.submit '送信', class: 'message-form-submit' %>
      </div>
      <% end %>


    </div>

  </div>

</div>

<%= render "shared/footer1" %>

app/views/managements/orders.html.erb
<%= render "shared/header3" %>

<div class="body-include-sidebar">

  <%= render "shared/sidebar2" %>

  <div class="main-body">
    <div class="main-body-body">

      <div class="main-body-title">
        <span style="color:#51456A">購入された商品一覧</span>
      </div>


      <ul class="seller-items">

        <% @orders.each do |order| %>
        <% @item = order.item %>
        <li class="seller-item">
          <%= render "shared/item_seller_small"%>
          <div class="manage-ordered-info">
            <div class="manage-ordered-info-left">
              <div class="order-user-info-title">購入情報</div>
              <div class="order-user-info">
                <div class="manage-ordered-day">購入日 <%= order.created_at.to_s(:datetime_jp) %></div>
                <div class="manage-ordered-count"><%= order.quantity %>セット</div>
                <div class="manage-ordered-price">¥<%= order.purchase_price %></div>
              </div>
            </div>
            <div class="manage-ordered-info-right">
              <div class="order-user-info-title">お届け先お客様情報</div>
              <div class="order-user-info">
                <div class="order-user-name"><%= order.shipping.last_name %><%= order.shipping.first_name %> (<%= order.shipping.last_name_kana %><%= order.shipping.first_name_kana %>) 様</div>
                <div class="order-user-zip">〒 <%= order.shipping.zip_code %><%= link_to 'このお客様にメッセージを送る', roomcreate_managements_path(order.user.id), method: :post,class:"new-message-link"%></div>
                <div class="order-user-address"><%= order.shipping.address %></div>
              </div>
            </div>
          </div>
        </li>
        <% end %>

      </ul>

    </div>

  </div>
</div>

</div>

<%= render "shared/footer2" %>

app/views/managements/roomindex.html.erb
<%= render "shared/header3" %>


<div class="body-include-sidebar">


  <%= render "shared/sidebar2" %>


  <div class="main-body">


    <div class="main-body-body">

      <div class="main-body-title">
        <span style="color:#51456A">メッセージ一覧</span>
      </div>

      <ul class="seller-items">

        <% @rooms.each do |room| %>
        <li class="seller-item-room">
          <%= room.user.profile.last_name %><%= room.user.profile.first_name %> 様
          <%= link_to '>>お客様とのメッセージ',messageindex_managements_path(room.id),class:"manage-room-link"%>
        </li>
        <% end %>

      </ul>

    </div>

  </div>

</div>

<%= render "shared/footer1" %>

app/views/managements/top.html.erb
<%= render "shared/header3" %>

<div class="body-include-sidebar">

  <%= render "shared/sidebar2" %>

  <div class="main-body">
    <div class="notice"><%= notice %></div>

    <div class="main-body-body">

      <div class="main-body-title">
        <span style="color:#51456A">販売者管理ページ</span>
      </div>

      <div class="main-body-sub-title">
        <span style="color:#51456A">販売者情報</span>
      </div>

      <div class="seller-show-up">
        <div class="seller-show-images">
          <%= image_tag  current_seller.store.image, class: "seller-show-image" %>
        </div>
        <div class="seller-show-info">
          <div class="seller-show-row1">
            <div class="seller-show-row1-left">
              <div class="seller-show-name"><b><%= current_seller.store_name %></b></div>
              <div class="seller-show-category"><%= current_seller.store.shopcategory.name %></div>
            </div>
          </div>
          <div class="seller-show-text">
            <%=  current_seller.store.information %>
          </div>
          <div class="seller-show-row2">
            ・〒<%=  current_seller.store.zip_code %> <%=  current_seller.store.address %>
          </div>
          <div class="seller-show-row2">
            ・Tel <%=  current_seller.store.phone_number %>
          </div>
          <div class="seller-show-row2">
            ・公式サイト
            <%= link_to current_seller.store.url, current_seller.store.url ,class: "seller-show-link"%>
          </div>
        </div>
      </div>

      <div class="main-body-sub-title">
        <span style="color:#51456A;margin-right:20px">販売商品一覧</span>
        <%= link_to '新規出品', new_item_path , class: "for-registration-red-btn" %>
      </div>

      <ul class=item-lists>

        <% @items.each do |item| %>
        <%= render partial: "shared/item_seller_middle", locals: {item: item }%>
        <% end %>

      </ul>


    </div>

  </div>

</div>

<%= render "shared/footer1" %>